version: '3'
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: mydatabase
    ports:
      - "3306:3306"
  
  api:
    build: .
    environment:
      DATABASE_URL: mysql+pymysql://root:example@db/mydatabase
    depends_on:
      - db