version: '3.8'  # Specify the Docker Compose version

services:
  api:
    build:
      context: C:\Users\neboc\Desktop\capstone
      dockerfile: Dockerfile
    depends_on:
      db:
        condition: service_healthy
    environment:
      ENV: development
    networks:
      - default
    ports:
      - "5000:5000"
    volumes:
      - type: bind
        source: C:\Users\neboc\Desktop\capstone
        target: /app
        bind:
          create_host_path: true

  db:
    container_name: api_db
    environment:
      MYSQL_DATABASE: mydatabase
      MYSQL_ROOT_PASSWORD: example
    image: mysql
    networks:
      - default
    ports:
      - "3306:3306"
    restart: always

networks:
  default:
    name: capstone_default
