version: '3.8'

services:
  api:
    build:
      context: .  # This should point to the directory containing your Dockerfile and app code
    ports:
      - "5000:5000"
    volumes:
      - type: bind
        source: .
        target: /app
    environment:
      ENV: development

  db:
    image: mysql
    environment:
      MYSQL_DATABASE: mydatabase
      MYSQL_ROOT_PASSWORD: example
    ports:
      - "3306:3306"
    restart: always
