services:
  mysql-db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  fastapi-api:
    build: .
    depends_on:
      - mysql-db
    ports:
      - "8000:8000"

volumes:
  mysql-data: